services:
  source_db:
    image: postgres:16
    container_name: source_db
    restart: always
    environment:
      - POSTGRES_DB=${SRC_POSTGRES_DB}
      - POSTGRES_USER=${SRC_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SRC_POSTGRES_PASSWORD}
    ports:
      - ${SRC_POSTGRES_PORT}:5432
    volumes:
      - ./source_data:/docker-entrypoint-initdb.d
      - source-volume:/var/lib/postgresql/data

  staging_db:
    image: postgres:16
    container_name: staging_db
    restart: always
    environment:
      - POSTGRES_DB=${STG_POSTGRES_DB}
      - POSTGRES_USER=${STG_POSTGRES_USER}
      - POSTGRES_PASSWORD=${STG_POSTGRES_PASSWORD}
    ports:
      - ${STG_POSTGRES_PORT}:5432
    volumes:
      - ./staging_data:/docker-entrypoint-initdb.d
      - staging-volume:/var/lib/postgresql/data

  warehouse_db:
    image: postgres:16
    container_name: warehouse_db
    restart: always
    environment:
      - POSTGRES_DB=${WH_POSTGRES_DB}
      - POSTGRES_USER=${WH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${WH_POSTGRES_PASSWORD}
    ports:
      - ${WH_POSTGRES_PORT}:5432
    volumes:
      - ./warehouse_data:/docker-entrypoint-initdb.d
      - warehouse-volume:/var/lib/postgresql/data

volumes:
  source-volume:
  staging-volume:
  warehouse-volume:
